sudo: required
dist: trusty
language: rust

matrix:
  include:
    # optional feature variations
    # we want full coverage, include all features...
    - rust: stable
      env: RUST_BACKTRACE=full
           RUN_KCOV=1

    # min rust version
    # - rust: 1.14.0
    - rust: beta
      env: RUST_BACKTRACE=full

    # macos
    - os: osx
      rust: stable
      env: RUST_BACKTRACE=full

    # nightly
    - rust: nightly
      env: RUST_BACKTRACE=full

    # clippy
    - rust: nightly
      env: RUST_BACKTRACE=full
      before_install:
        - cargo install clippy --force
      script:
        - scripts/run_clippy.sh

    - rust: nightly
      env: RUST_BACKTRACE=full
      before_install:
        - cargo install rustfmt-nightly --force
      script:
        - cargo fmt --all -- --write-mode=diff

    - rust: stable
      env: TDNS_BIND_PATH="../../bind-9.11.0-P1/bin/named/named"
           RUST_BACKTRACE=full
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/install_openssl_deb.sh ; fi
        - scripts/install_bind.sh
      script:
        - cargo test --manifest-path compatibility-tests/Cargo.toml --no-default-features --features=bind

  allow_failures:
    - rust: nightly

before_install:
  - bash -c '[[ "$TRAVIS_OS_NAME" == "linux" ]] && then scripts/install_openssl_deb.sh'

script:
  - scripts/run_tests.sh

after_success: scripts/run_kcov.sh
